package com.asotec.riesgos.entity;
// Generated 03/04/2018 13:54:20 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GenOficina generated by hbm2java
 */
@Entity
@Table(name = "gen_oficina",
        schema = "public"
)
public class GenOficina implements java.io.Serializable {

    private long codOficina;
    private String nomOficina;
    private char stsOficina;
    private Character stsTipo;
    private String dirOficina;
    private String dir2Oficina;
    private String telTrabajo;
    private Character stsConexion;
    private String nomGerente;
    private Long codAgenciaUaf;
    private Integer codAgenciaSeps;
    private String codCuentaTransfDeudora;
    private String codCuentaTransfAcreedora;
//    private Short codCanton;

    public GenOficina() {
    }

    public GenOficina(long codOficina, String nomOficina, char stsOficina) {
        this.codOficina = codOficina;
        this.nomOficina = nomOficina;
        this.stsOficina = stsOficina;
    }

    public GenOficina(long codOficina, String nomOficina, char stsOficina, Character stsTipo, String dirOficina, String dir2Oficina, String telTrabajo, Character stsConexion, String nomGerente, Long codAgenciaUaf, Integer codAgenciaSeps, String codCuentaTransfDeudora, String codCuentaTransfAcreedora) {
        this.codOficina = codOficina;
        this.nomOficina = nomOficina;
        this.stsOficina = stsOficina;
        this.stsTipo = stsTipo;
        this.dirOficina = dirOficina;
        this.dir2Oficina = dir2Oficina;
        this.telTrabajo = telTrabajo;
        this.stsConexion = stsConexion;
        this.nomGerente = nomGerente;
        this.codAgenciaUaf = codAgenciaUaf;
        this.codAgenciaSeps = codAgenciaSeps;
        this.codCuentaTransfDeudora = codCuentaTransfDeudora;
        this.codCuentaTransfAcreedora = codCuentaTransfAcreedora;
        
    }

    @Id

    @Column(name = "cod_oficina", unique = true, nullable = false, precision = 2, scale = 0)
    public long getCodOficina() {
        return this.codOficina;
    }

    public void setCodOficina(long codOficina) {
        this.codOficina = codOficina;
    }

    @Column(name = "nom_oficina", nullable = false, length = 50)
    public String getNomOficina() {
        return this.nomOficina;
    }

    public void setNomOficina(String nomOficina) {
        this.nomOficina = nomOficina;
    }

    @Column(name = "sts_oficina", nullable = false, length = 1)
    public char getStsOficina() {
        return this.stsOficina;
    }

    public void setStsOficina(char stsOficina) {
        this.stsOficina = stsOficina;
    }

    @Column(name = "sts_tipo", length = 1)
    public Character getStsTipo() {
        return this.stsTipo;
    }

    public void setStsTipo(Character stsTipo) {
        this.stsTipo = stsTipo;
    }

    @Column(name = "dir_oficina", length = 100)
    public String getDirOficina() {
        return this.dirOficina;
    }

    public void setDirOficina(String dirOficina) {
        this.dirOficina = dirOficina;
    }

    @Column(name = "dir2_oficina", length = 100)
    public String getDir2Oficina() {
        return this.dir2Oficina;
    }

    public void setDir2Oficina(String dir2Oficina) {
        this.dir2Oficina = dir2Oficina;
    }

    @Column(name = "tel_trabajo", length = 20)
    public String getTelTrabajo() {
        return this.telTrabajo;
    }

    public void setTelTrabajo(String telTrabajo) {
        this.telTrabajo = telTrabajo;
    }

    @Column(name = "sts_conexion", length = 1)
    public Character getStsConexion() {
        return this.stsConexion;
    }

    public void setStsConexion(Character stsConexion) {
        this.stsConexion = stsConexion;
    }

    @Column(name = "nom_gerente", length = 100)
    public String getNomGerente() {
        return this.nomGerente;
    }

    public void setNomGerente(String nomGerente) {
        this.nomGerente = nomGerente;
    }

    @Column(name = "cod_agencia_uaf", precision = 10, scale = 0)
    public Long getCodAgenciaUaf() {
        return this.codAgenciaUaf;
    }

    public void setCodAgenciaUaf(Long codAgenciaUaf) {
        this.codAgenciaUaf = codAgenciaUaf;
    }

    @Column(name = "cod_agencia_seps", precision = 8, scale = 0)
    public Integer getCodAgenciaSeps() {
        return this.codAgenciaSeps;
    }

    public void setCodAgenciaSeps(Integer codAgenciaSeps) {
        this.codAgenciaSeps = codAgenciaSeps;
    }

    @Column(name = "cod_cuenta_transf_deudora", length = 20)
    public String getCodCuentaTransfDeudora() {
        return this.codCuentaTransfDeudora;
    }

    public void setCodCuentaTransfDeudora(String codCuentaTransfDeudora) {
        this.codCuentaTransfDeudora = codCuentaTransfDeudora;
    }

    @Column(name = "cod_cuenta_transf_acreedora", length = 20)
    public String getCodCuentaTransfAcreedora() {
        return this.codCuentaTransfAcreedora;
    }

    public void setCodCuentaTransfAcreedora(String codCuentaTransfAcreedora) {
        this.codCuentaTransfAcreedora = codCuentaTransfAcreedora;
    }

    @Override
    public String toString() {
        return "GenOficina{" + "codOficina=" + codOficina + ", nomOficina=" + nomOficina + ", stsOficina=" + stsOficina + ", stsTipo=" + stsTipo + ", dirOficina=" + dirOficina + ", dir2Oficina=" + dir2Oficina + ", telTrabajo=" + telTrabajo + ", stsConexion=" + stsConexion + ", nomGerente=" + nomGerente + ", codAgenciaUaf=" + codAgenciaUaf + ", codAgenciaSeps=" + codAgenciaSeps + ", codCuentaTransfDeudora=" + codCuentaTransfDeudora + ", codCuentaTransfAcreedora=" + codCuentaTransfAcreedora+ '}';
    }

}
